<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name'          => 'Camisa Sublimação Full Print – Exclusiva',
                'slug'          => 'camisa-sublimacao-full-print-exclusiva',
                'price'         => 49.90,
                'tag'           => 'MAIS VENDIDO',
                'category'      => 'sublimacao',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG', 'XG'],
                'colors'        => ['black', 'white', 'grey'],
                'rating'        => 5,
                'reviews_count' => 128,
                'description'   => 'Camisa produzida em tecido 100% poliéster com estamparia full print de alta qualidade. Cores vibrantes, toque leve e secagem rápida. Ideal para eventos, empresas e esportes.',
                'images'        => ['images/sublimacao_mockup.png','images/camisas_exclusivas.png','images/dtf_mockup.png','images/serigrafia_mockup.png','images/rumus_hero_model.png'],
                'bullets'       => ['Estampa full print de alta definição','Tecido leve e confortável','Secagem rápida','Ideal para eventos e uso diário'],
                'specs'         => ['Material'=>'100% Poliéster','Gramatura'=>'150g/m²','Tipo de Estampa'=>'Sublimação Full Print','Modelagem'=>'Tradicional','Gênero'=>'Unissex'],
                'cares'         => ['Lavar à mão ou máquina em ciclo delicado','Não usar alvejante','Não deixar de molho','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa Serigrafia Tradicional',
                'slug'          => 'camisa-serigrafia-tradicional',
                'price'         => 34.90,
                'tag'           => '',
                'category'      => 'serigrafia',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG'],
                'colors'        => ['black', 'white', 'grey'],
                'rating'        => 5,
                'reviews_count' => 152,
                'description'   => 'Camisa personalizada em Silk Screen tradicional com tintas à base de água de alta cobertura. A escolha perfeita para grandes lotes, uniformes e eventos.',
                'images'        => ['images/serigrafia_mockup.png','images/dtf_mockup.png','images/sublimacao_mockup.png','images/camisas_exclusivas.png','images/rumus_hero_model.png'],
                'bullets'       => ['Alta durabilidade da estampa (Silk Screen)','Tecido 100% Algodão Confortável','Excelente custo benefício para grandes tiragens','Corte clássico confortável'],
                'specs'         => ['Material'=>'100% Algodão Cardado/Penteado','Gramatura'=>'160g/m²','Tipo de Estampa'=>'Serigrafia / Silk Screen','Modelagem'=>'Tradicional Confort','Gênero'=>'Unissex'],
                'cares'         => ['Lavar normalmente na máquina','Passar ferro do avesso se necessário','Não alvejar','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa DTF Estampa Premium',
                'slug'          => 'camisa-dtf-estampa-premium',
                'price'         => 39.90,
                'tag'           => '',
                'category'      => 'dtf',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG', 'XG', 'XGG'],
                'colors'        => ['black', 'red', 'purple'],
                'rating'        => 5,
                'reviews_count' => 64,
                'description'   => 'Camisa de algodão premium com estampa em alta definição aplicada via tecnologia DTF (Direct to Film). Toque emborrachado ultra fino e cores ultra realistas.',
                'images'        => ['images/dtf_mockup.png','images/serigrafia_mockup.png','images/sublimacao_mockup.png','images/camisas_exclusivas.png','images/rumus_hero_model.png'],
                'bullets'       => ['Estampa com alta elasticidade','Tecido 100% Algodão Fio 30.1','Excelente acabamento costurado','Ideal para marcas de roupa e uso casual'],
                'specs'         => ['Material'=>'100% Algodão Premium Penteado','Gramatura'=>'165g/m²','Tipo de Estampa'=>'DTF HD Emborrachado','Modelagem'=>'Casual / Streetwear','Gênero'=>'Unissex'],
                'cares'         => ['Lavar do avesso para proteger a estampa','Não passar o ferro diretamente sobre o DTF','Não utilizar secadora de roupas','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Ecobag Personalizada Algodão Cru',
                'slug'          => 'ecobag-personalizada-algodao-cru',
                'price'         => 19.90,
                'tag'           => '',
                'category'      => 'ecobag',
                'type'          => 'unissex',
                'sizes'         => ['M', 'G'],
                'colors'        => ['white', 'grey'],
                'rating'        => 5,
                'reviews_count' => 48,
                'description'   => 'Ecobag feita de algodão cru 100% ecológico, super resistente com alças costuradas e reforçadas. Ideal para personalização com sua marca, eventos ou uso cotidiano.',
                'images'        => ['images/ecobag_mockup.png','images/rumus_hero_model.png'],
                'bullets'       => ['Material 100% algodão ecológico','Costura reforçada de alta durabilidade','Tamanho ideal para compras e pertences cotidianos','Estamparia ecológica de alta fidelidade'],
                'specs'         => ['Material'=>'100% Algodão Cru','Gramatura'=>'220g/m²','Tamanho'=>'38x40cm','Tipo de Estampa'=>'Serigrafia / DTF','Gênero'=>'Unissex'],
                'cares'         => ['Lavar à mão para evitar encolhimento','Não utilizar alvejantes clorados','Passar ferro morno pelo avesso','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa Sublimação Degradê',
                'slug'          => 'camisa-sublimacao-degrade',
                'price'         => 49.90,
                'tag'           => 'MAIS VENDIDO',
                'category'      => 'sublimacao',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG'],
                'colors'        => ['black', 'blue', 'purple'],
                'rating'        => 5,
                'reviews_count' => 92,
                'description'   => 'Camiseta com efeito degradê contínuo estampado em alta resolução. Fabricada em malha Dry esportiva que proporciona frescor e leveza com caimento perfeito.',
                'images'        => ['images/camisas_exclusivas.png','images/sublimacao_mockup.png','images/dtf_mockup.png','images/rumus_hero_model.png'],
                'bullets'       => ['Degradê suave em alta resolução','Tecido Dry-Fit antitranspirante','Não amassa e não desbota','Ideal para corrida, academia e eventos'],
                'specs'         => ['Material'=>'100% Poliéster Dry-Fit','Gramatura'=>'145g/m²','Tipo de Estampa'=>'Sublimação Total','Modelagem'=>'Esportiva','Gênero'=>'Unissex'],
                'cares'         => ['Lavar com água fria','Não alvejar e não secar em tambor','Não necessita passar a ferro','Secar no varal'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa Serigrafia Minimalista',
                'slug'          => 'camisa-serigrafia-minimalista',
                'price'         => 29.90,
                'tag'           => '',
                'category'      => 'serigrafia',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG'],
                'colors'        => ['black', 'white'],
                'rating'        => 5,
                'reviews_count' => 38,
                'description'   => 'Estampa minimalista de alta precisão em malha 100% algodão premium penteado. Visual limpo, sofisticado e extremamente confortável para uso diário.',
                'images'        => ['images/rumus_hero_model.png','images/serigrafia_mockup.png','images/dtf_mockup.png'],
                'bullets'       => ['Algodão premium penteado fio 30.1','Estampa em silk toque zero','Costura reforçada de ombro a ombro','Design minimalista exclusivo'],
                'specs'         => ['Material'=>'100% Algodão Penteado 30.1','Gramatura'=>'165g/m²','Tipo de Estampa'=>'Serigrafia Toque Zero','Modelagem'=>'Modern Fit','Gênero'=>'Unissex'],
                'cares'         => ['Lavar do avesso em ciclo leve','Não passar ferro quente sobre a estampa','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa DTF Full Color',
                'slug'          => 'camisa-dtf-full-color',
                'price'         => 39.90,
                'tag'           => '',
                'category'      => 'dtf',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG', 'XG'],
                'colors'        => ['black', 'purple', 'red'],
                'rating'        => 5,
                'reviews_count' => 76,
                'description'   => 'Camiseta com estampa DTF em cores completas, alta fidelidade e graduações perfeitas de degradês. A escolha ideal para artes complexas, ilustrações e fotos.',
                'images'        => ['images/dtf_mockup.png','images/camisas_exclusivas.png','images/serigrafia_mockup.png'],
                'bullets'       => ['Impressão colorida de altíssima definição','Excelente durabilidade em lavagens','Toque macio e flexível da estampa','Tecido confort premium de algodão'],
                'specs'         => ['Material'=>'100% Algodão Premium','Gramatura'=>'160g/m²','Tipo de Estampa'=>'DTF Full Color HD','Modelagem'=>'Casual / Streetwear','Gênero'=>'Unissex'],
                'cares'         => ['Lavar do avesso','Não usar alvejante e secadoras','Passar ferro do avesso'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Ecobag Personalizada Tecido Preto',
                'slug'          => 'ecobag-personalizada-tecido-preto',
                'price'         => 22.90,
                'tag'           => '',
                'category'      => 'ecobag',
                'type'          => 'unissex',
                'sizes'         => ['M', 'G'],
                'colors'        => ['black'],
                'rating'        => 5,
                'reviews_count' => 31,
                'description'   => 'Ecobag confeccionada em tecido de sarja preta de alta gramatura. Acabamento premium com costura em cruz nas alças, perfeita para carregar peso com muito estilo.',
                'images'        => ['images/ecobag_mockup.png','images/rumus_hero_model.png'],
                'bullets'       => ['Sarja preta de algodão encorpado','Alças reforçadas costura X','Cores de estampa destacadas sobre fundo preto','Lavável e reutilizável'],
                'specs'         => ['Material'=>'100% Algodão Sarja Preto','Gramatura'=>'240g/m²','Tamanho'=>'38x40cm','Tipo de Estampa'=>'DTF / Serigrafia Plasti-sol','Gênero'=>'Unissex'],
                'cares'         => ['Lavar preferencialmente à mão','Secar naturalmente no varal','Passar ferro morno do avesso'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa Sublimação Esportiva',
                'slug'          => 'camisa-sublimacao-esportiva',
                'price'         => 54.90,
                'tag'           => '',
                'category'      => 'sublimacao',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG', 'XG', 'XGG'],
                'colors'        => ['black', 'red', 'blue', 'green'],
                'rating'        => 5,
                'reviews_count' => 87,
                'description'   => 'Camiseta desenvolvida especialmente para a prática esportiva, com tecnologia Dry-Fit que absorve o suor e mantém o corpo seco durante os treinos.',
                'images'        => ['images/uniformes.png','images/sublimacao_mockup.png','images/dtf_mockup.png','images/serigrafia_mockup.png','images/rumus_hero_model.png'],
                'bullets'       => ['Tecnologia Dry-Fit respirável','Costuras planas anti-assaduras','Proteção UV 50+','Secagem ultra rápida'],
                'specs'         => ['Material'=>'100% Poliamida / Poliéster Dry','Gramatura'=>'130g/m²','Tipo de Estampa'=>'Sublimação Esportiva','Modelagem'=>'Atlética','Gênero'=>'Unissex'],
                'cares'         => ['Lavar com água fria e sabão neutro','Não utilizar amaciante de tecidos','Não necessita passar a ferro','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa Serigrafia Estampa Grande',
                'slug'          => 'camisa-serigrafia-estampa-grande',
                'price'         => 34.90,
                'tag'           => '',
                'category'      => 'serigrafia',
                'type'          => 'unissex',
                'sizes'         => ['P', 'M', 'G', 'GG'],
                'colors'        => ['white', 'grey', 'black'],
                'rating'        => 5,
                'reviews_count' => 114,
                'description'   => 'Camisa estampada em serigrafia tradicional com cobertura total de estampa frontal e/ou traseira. Excelente definição e altíssima durabilidade mesmo com lavagens intensas.',
                'images'        => ['images/serigrafia_mockup.png','images/dtf_mockup.png','images/sublimacao_mockup.png'],
                'bullets'       => ['Estampa com grande área de cobertura','Tinta plastisol de alto relevo ou base de água de alta cobertura','Tecido de algodão super macio','Ideal para bandas, marcas streetwear e eventos'],
                'specs'         => ['Material'=>'100% Algodão Premium Penteado','Gramatura'=>'165g/m²','Tipo de Estampa'=>'Silk Screen Tradicional','Modelagem'=>'Streetwear Oversized / Casual','Gênero'=>'Unissex'],
                'cares'         => ['Lavar na máquina do avesso','Não passar o ferro sobre a estampa','Secar à sombra'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Camisa DTF Infantil',
                'slug'          => 'camisa-dtf-infantil',
                'price'         => 34.90,
                'tag'           => '',
                'category'      => 'dtf',
                'type'          => 'infantil',
                'sizes'         => ['P', 'M', 'G'],
                'colors'        => ['black', 'white', 'red', 'blue'],
                'rating'        => 5,
                'reviews_count' => 43,
                'description'   => 'Camiseta infantil super macia e antialérgica com estamparia DTF flexível e confortável. Livre de toques ásperos na pele das crianças.',
                'images'        => ['images/dtf_mockup.png','images/sublimacao_mockup.png'],
                'bullets'       => ['Malha antialérgica 100% Algodão','Estampa macia e super elástica','Cores alegres e vibrantes de longa duração','Costuras macias anti-irritação'],
                'specs'         => ['Material'=>'100% Algodão Antialérgico','Gramatura'=>'150g/m²','Tipo de Estampa'=>'DTF Flexível','Modelagem'=>'Infantil Confortável','Gênero'=>'Unissex'],
                'cares'         => ['Lavar do avesso em ciclo suave','Não alvejar','Não secar em secadora'],
                'is_active'     => true,
            ],
            [
                'name'          => 'Ecobag Personalizada Ecológica',
                'slug'          => 'ecobag-personalizada-ecologica',
                'price'         => 19.90,
                'tag'           => '',
                'category'      => 'ecobag',
                'type'          => 'unissex',
                'sizes'         => ['M', 'G'],
                'colors'        => ['white', 'green'],
                'rating'        => 5,
                'reviews_count' => 56,
                'description'   => 'Ecobag sustentável produzida com fios reciclados de algodão e fibras de garrafa PET (tecido ecológico reciclado). Leve sustentabilidade e consciência ecológica para sua rotina.',
                'images'        => ['images/ecobag_mockup.png','images/rumus_hero_model.png'],
                'bullets'       => ['Tecido reciclado ecológico (Algodão + Fibras PET)','Produto sustentável consciente','Super resistente e reutilizável','Estampa com corantes à base de água orgânicos'],
                'specs'         => ['Material'=>'50% Algodão Reciclado / 50% Fibras PET','Gramatura'=>'200g/m²','Tamanho'=>'38x40cm','Tipo de Estampa'=>'Serigrafia ecológica','Gênero'=>'Unissex'],
                'cares'         => ['Lavar com sabão neutro e secar à sombra','Não passar o ferro muito quente'],
                'is_active'     => true,
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
